function pos_sym = fk_pos_func(in1)
%FK_POS_FUNC
%    POS_SYM = FK_POS_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Nov-2025 20:23:43

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
t2 = sin(q2);
t3 = -q3;
t4 = t2.*1.4e+2;
t5 = q2+t3;
t6 = q4+t5;
t7 = sin(t5);
t8 = sin(t6);
t9 = t7.*1.33e+2;
t10 = t8.*1.09e+2;
t11 = t4+t9+t10;
pos_sym = [t11.*cos(q1).*(-1.0./1.0e+3);t11.*sin(q1).*(-1.0./1.0e+3);cos(q2).*(7.0./5.0e+1)+cos(t5).*(1.33e+2./1.0e+3)+cos(t6).*(1.09e+2./1.0e+3)+4.355e-2];
end
